### PR TITLE
Major Architecture revision

### PR DESCRIPTION
**Pull request by JorgenVanDerVelde**
In this pull request I make a proposal for the architecture of CoMPAS. Following have been updated:

- Gitbook structure. The final result can be viewed on a [temporary gitbook](https://jorgen-van-der-velde.gitbook.io/compas-temporary/compas-architecture/readme)
- Functional architecture: description of context and decomposition
- TEchnical architecture: description of the docker deployment and CI/CD
- Glossary update
- Readme update to reflect the the architecture must be updated
- Page describing the technical decisions
- All research moved to the apendices

The three pending pull requests have been merged in this pull request.

### CODE REVIEW

**Comment by Flurb** [comment]
Commit must be signed off to pass DCO check :)
So each commit should have the flag --signoff, like this:
`git commit -a "message" --signoff`

**Comment by Flurb** [comment]
DCO check issue has been fixed!

**Comment by Flurb** [comment]
Looks good!
Few questions:
- Why Gitbook over Github Pages?
- Few typo's (CoMPASS instead of CoMPAS is pretty common)
- AA(A) is on the roadmap, in the "Design decisions" section it's stated as "no AA(A)"
- Technology image needs an update

**Comment by JorgenVanDerVelde** [comment]
> Looks good!
> Few questions:
> 
> * Why Gitbook over Github Pages?

I cannot get a custom table of contents on Github pages. The automatic process clutters the table of contents/menu, resulting in a unclear site. A solution is to use gitbook, unless a way is found to control the table of contents/menu

> * Few typo's (CoMPASS instead of CoMPAS is pretty common)

Removed CoMPASS

> * AA(A) is on the roadmap, in the "Design decisions" section it's stated as "no AA(A)"

Rephrased

> * Technology image needs an update

Rob will provide a new image

**Comment by JorgenVanDerVelde** [comment]
Navigation updated for github pages

**Review by Flurb — APPROVED** [review]
Discussed + looks good!

**Pull request merged**
