### PR TITLE
Microservice choice explanation

### PR DESCRIPTION
**Pull request by Flurb**

### CODE REVIEW

**Comment by Flurb** [comment]
Please check 1a181f4

**Review by LRBH10 — APPROVED** [review]

**Review by syllamoh — COMMENTED** [review]
Hello,
Juste a reminder Quarkus, as Spring, is a JAVA framework. It might use a different VM from the one used generally for spring, but it remains a JAVA framework. 

I noticed that you use the term spring as it was equals to java when you say:

- java is pretty slow ... compared to what in the context of "pros & cons for Quarkus and Spring" ?
- java annotation .... when you highlight "pros for spring"

Beside neither Quarkus nor Spring implements Servlets or XML processing routines. They only supports those technologies from other libraries. Hence they have no impact on the performance of those technologies. And Developer is free use the support or not even when using one of the frameworks.

So far in my understand, the real deal is XML processing. Comparison between XML processing technologies is most relevant.

**Comment by LRBH10** [comment]
the advantage of Quarkus that it can be built directly to native.

you can find the documentation here :  https://quarkus.io/guides/building-native-image  (GraalVM)

Also for development purpose it provide a watching mode which simplify the work.

**Comment by Flurb** [comment]
> Hello,
> Juste a reminder Quarkus, as Spring, is a JAVA framework. It might use a different VM from the one used generally for spring, but it remains a JAVA framework.
> 
> I noticed that you use the term spring as it was equals to java when you say:
> 
> * java is pretty slow ... compared to what in the context of "pros & cons for Quarkus and Spring" ?
> * java annotation .... when you highlight "pros for spring"
> 
> Beside neither Quarkus nor Spring implements Servlets or XML processing routines. They only supports those technologies from other libraries. Hence they have no impact on the performance of those technologies. And Developer is free use the support or not even when using one of the frameworks.
> 
> So far in my understand, the real deal is XML processing. Comparison between XML processing technologies is most relevant.

True that both framework are Java oriented and each microservice can indeed use their own framework (advantage in a microservice architecture!), but for maintenance for example it's more handy that we are using the same technologies.

As stated before and at the beginning of the project, we chose Quarkus because of multiple reasons, see also: https://com-pas.github.io/compas-architecture/TECHNOLOGY.html :)

**Comment by syllamoh** [comment]
Hi @Flurb 
My points is about the pull request. I'm not arguing about which Framework is super performance for specific action. Less relevant compare to what is the aim of ComPas (globally processing XML files), at least for CIM and the SCT.

Those components won't be eager in IO consuming. Even this was that case these frameworks won't make any significant difference as their support of RESTful style relies Servlets.

Again completely focusing on the pull request, it seems to me while reading the text that you equate Spring=Java.
_<<
I noticed that you use the term spring as it was equals to java when you say:

    java is pretty slow ... compared to what in the context of "pros & cons for Quarkus and Spring" ?
    java annotation .... when you highlight "pros for spring"
>>_

At the community call, as I said and explained why, at RTE we'll be using Spring if the the underlying language is JAVA to implement the compas-sct.

**Comment by Flurb** [comment]
> Hi @Flurb
> My points is about the pull request. I'm not arguing about which Framework is super performance for specific action. Less relevant compare to what is the aim of ComPas (globally processing XML files), at least for CIM and the SCT.
> 
> Those components won't be eager in IO consuming. Even this was that case these frameworks won't make any significant difference as their support of RESTful style relies Servlets.
> 
> Again completely focusing on the pull request, it seems to me while reading the text that you equate Spring=Java.
> "
> java is pretty slow ... compared to what in the context of "pros & cons for Quarkus and Spring" ?
> java annotation .... when you highlight "pros for spring"
> "
> 
> At the community call, as I said and explained why, at RTE we'll be using Spring if the the underlying language is JAVA to implement the compas-sct.

Ah got it.
I made a weird comparison apparently!
Spring is Java, but Java is not Spring ofcourse.
My bad :)

**Pull request closed without merging**
