### PR TITLE
Xml processing choice explanation

### PR DESCRIPTION
**Pull request by Flurb**

### CODE REVIEW

**Comment by Flurb** [comment]
Please check revision 64c9e27

**Comment by syllamoh** [comment]
Hi
Concerning RisEclipse and Schematron, in my opinion these solutions are not comparable. Schematron, as XML schema and Relax NG, are structural grammar validation language. Those technologies need software to apply constrains they define. RisEclipse is an application. It uses **OCL** to express its constrains.
So it's better comparing OCL and Schematron for XML processing. As I've already said ever since in the survey, in my opinion, it's better using XML technologies to process XML

**Review by LRBH10 — APPROVED** [review]

**Comment by ADehouck** [comment]
Hi,
I am Aurelie DEHOUCK from EDF, part of RISECLIPSE team.
I wanted to argue in favor or RISECLIPSE vs schematron :
    - the validation rules are already available, whereas you will have to re-develop all with schematron. 
    - with OCL you can express the rules outside of the code, and non-developper specialists can understand / write them directly,
    - We have launched in 2021 a task force in IEC TC57/WG10 (working on IEC 61850), in oder to standardize OCL rules as "code components" of the standard. Those standard OCL rules will be written by the standard experts, and joined to the pdf standard, like the XSD for SCL 
    - RISECLIPSE was used during last IEC 61850 IOPs in 2019, in Charlotte, and has found many of the SCL issues, proving its capacity of validation, and maturity 
    - (more technically) with OCL you navigate into your file at a model level (understand a graph) : this is very usefull in files like SCL, where you have many Inside references (for example IED LN to LNodeType…)
    - our Community is open : you are welcome to participate !

**Comment by Flurb** [comment]
> Hi
> Concerning RisEclipse and Schematron, in my opinion these solutions are not comparable. Schematron, as XML schema and Relax NG, are structural grammar validation language. Those technologies need software to apply constrains they define. RisEclipse is an application. It uses **OCL** to express its constrains.
> So it's better comparing OCL and Schematron. As I've already said ever since in the survey, in my opinion, it's better using XML technologies to process XML

@syllamoh 
You're completely right.
We are using the combination JAXB / RDF4J now for processing the XML data. RDF4J is used for incoming CIM files (using the RDF framework), JAXB is used for processing / validating the SCL files. In combination with the underlying BaseX database for storing the data it's enough for the processing XML choice. Schematron/RiseClipse is out of sight and not used anymore.

I will edit the page. :)

**Comment by Sander3003** [comment]
Users can always add a microservice with RiseClipse inside for additional checking of the SCL contrains.

**Pull request closed without merging**
