### PR TITLE
Database choice explanation

### PR DESCRIPTION
**Pull request by Flurb**

### CODE REVIEW

**Comment by Flurb** [comment]
Please check revision 6a3893a :)

**Comment by syllamoh** [comment]
Hi
What you meant by : _BaseX **gave** SirixDB as a good alternative in case we want a NoSQL database with versioning mechanism_. ?

**Comment by Flurb** [comment]
Hi @syllamoh , good question!
BaseX doesn't have a versioning mechanism built in, this can be achieved by running multiple BaseX instances. For example, one for the current versions, and one for past versions.
If we do want to have a database with versioning mechanism, then BaseX gave us the SirixDB as an alternative.

But I think running multiple BaseX instances is fine. It's a lightweight database and it shouldn't matter to much to run multiple instances.

**Comment by Flurb** [comment]
Anyone has some more feedback? :)

**Pull request closed without merging**
